# Generated by Django 3.2.10 on 2022-01-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20220108_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='label',
        ),
    ]
