# Generated by Django 3.2.10 on 2022-01-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_auto_20220108_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='label',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='label',
            new_name='name',
        ),
    ]
