# Generated by Django 3.2.10 on 2022-01-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_auto_20220108_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='type',
            field=models.CharField(default='clients', max_length=7),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type',
            field=models.CharField(default='projects', max_length=8),
        ),
    ]
